/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wordProcessor;

import javax.swing.text.rtf.RTFEditorKit;

/**
 *
 * @author spatel7043
 */
public class MainForm extends javax.swing.JFrame {

    private final RTFEditorKit rtfKit = new RTFEditorKit();

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();

        textArea.setEditorKit(rtfKit); //setting editor kit to rtfKit
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelForPage = new javax.swing.JPanel();
        TheTextArea = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextPane();
        topMenuBar = new javax.swing.JMenuBar();
        fileMenu = new FileMenu(this, textArea).getMenu();
        editMenu = new EditMenu().getMenu();
        fontChangeMenu = new FontTypeMenu().getMenu();
        changeFontSizeMenu = new FontSizeMenu().getMenu();
        formatMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 850));
        getContentPane().setLayout(new java.awt.FlowLayout());

        panelForPage.setBackground(new java.awt.Color(255, 255, 255));
        panelForPage.setFocusable(false);
        panelForPage.setPreferredSize(new java.awt.Dimension(575, 800));
        panelForPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TheTextArea.setViewportView(textArea);

        panelForPage.add(TheTextArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 435, 654));

        getContentPane().add(panelForPage);

        topMenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        topMenuBar.add(fileMenu);

        editMenu.add(fontChangeMenu);

        editMenu.add(changeFontSizeMenu);

        topMenuBar.add(editMenu);

        topMenuBar.add(formatMenu);

        setJMenuBar(topMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TheTextArea;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu changeFontSizeMenu;
    private javax.swing.JMenu fontChangeMenu;
    private javax.swing.JMenu formatMenu;
    private javax.swing.JPanel panelForPage;
    private javax.swing.JTextPane textArea;
    private javax.swing.JMenuBar topMenuBar;
    // End of variables declaration//GEN-END:variables
}